apiVersion: apps/v1
kind: Deployment

metadata:
  name: iot-dashboard
  namespace: iot

spec:
  replicas: 1

  selector:
    matchLabels:
      app: iot-dashboard

  template:
    metadata:
      labels:
        app: iot-dashboard

    spec:
      nodeSelector:
        role: control

      containers:
      - name: iot-dashboard
<<<<<<< HEAD
        image: wernes1/iot-dashboard:d8f2f4bc20071642b93dc281a43dbd8f95bbe04e
=======

        image: wernes1/iot-dashboard:d8f2f4bc20071642b93dc281a43dbd8f95bbe04e

>>>>>>> aa6e488 (pointing to new node. I'm migrating to k3s)
        imagePullPolicy: Always

        ports:
        - containerPort: 3000